    CREATE TABLE IF NOT EXISTS ACCOUNT(
        id BIGINT PRIMARY KEY,
        USERNAME VARCHAR(250) NOT NULL,
        PASSWORD VARCHAR(250) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS ORDERS(
        id BIGINT PRIMARY KEY,
        PRICE  FLOAT NOT NULL,
        QUANTITY INT NOT NULL,
        TYPE VARCHAR(250) NOT NULL,
        USERNAME VARCHAR(250) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS TRADE(
        id BIGINT PRIMARY KEY,
        PRICE  FLOAT NOT NULL,
        QUANTITY INT NOT NULL,
        BUYER VARCHAR(250) NOT NULL,
        SELLER VARCHAR(250) NOT NULL
    );